use anyhow::Result;

use crate::core::tracking::Tracker;

pub fn export(output_path: Option<&str>, days: u32) -> Result<()> {
    let tracker = Tracker::open(None)?;
    let summary = tracker.get_summary()?;
    let daily = tracker.get_daily(days)?;
    let by_method = tracker.get_by_method()?;

    let tokens_saved = summary
        .total_input_tokens
        .saturating_sub(summary.total_output_tokens);

    let daily_rows: String = daily
        .iter()
        .map(|d| {
            format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{:.1}%</td></tr>",
                d.date, d.commands, d.input_tokens, d.output_tokens, d.avg_savings
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let method_rows: String = by_method
        .iter()
        .map(|m| {
            format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{:.1}%</td></tr>",
                m.method, m.count, m.tokens_saved, m.avg_savings
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ZeroCTX Token Savings Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; background: #f8f9fa; }}
  h1 {{ color: #1a1a2e; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
  h2 {{ color: #16213e; margin-top: 30px; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin: 20px 0; }}
  .stat {{ background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }}
  .stat .value {{ font-size: 2em; font-weight: bold; color: #e94560; }}
  .stat .label {{ color: #666; margin-top: 4px; }}
  table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  th {{ background: #1a1a2e; color: white; padding: 12px; text-align: left; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #eee; }}
  tr:hover {{ background: #f0f0f0; }}
  .footer {{ margin-top: 40px; text-align: center; color: #999; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>ZeroCTX Token Savings Report</h1>

<div class="stats">
  <div class="stat"><div class="value">{}</div><div class="label">Commands</div></div>
  <div class="stat"><div class="value">{}</div><div class="label">Tokens Saved</div></div>
  <div class="stat"><div class="value">{:.1}%</div><div class="label">Avg Savings</div></div>
  <div class="stat"><div class="value">{}</div><div class="label">Input Tokens</div></div>
</div>

<h2>Savings by Method</h2>
<table>
<tr><th>Method</th><th>Uses</th><th>Tokens Saved</th><th>Avg Savings</th></tr>
{}
</table>

<h2>Daily Breakdown (Last {} Days)</h2>
<table>
<tr><th>Date</th><th>Commands</th><th>Input</th><th>Output</th><th>Savings</th></tr>
{}
</table>

<div class="footer">Generated by ZeroCTX v{}</div>
</body>
</html>"#,
        summary.total_commands,
        tokens_saved,
        summary.avg_savings_percent,
        summary.total_input_tokens,
        method_rows,
        days,
        daily_rows,
        env!("CARGO_PKG_VERSION"),
    );

    match output_path {
        Some(path) => {
            std::fs::write(path, &html)?;
            println!("Exported HTML report to {}", path);
        }
        None => {
            println!("{}", html);
        }
    }

    Ok(())
}
